"""Write database/seed_demo_district_offices.sql: one DEMO district desk per department for every one of the 55 districts.

Why: routing is district-aware (migration 005), so testing "a complaint from Rajgarh reaches Rajgarh" needs offices in Rajgarh. These rows are INVENTED
(office names copy the Bhopal demo desk and say "(DEMO)"). They are for the private local test database and demos only. Never run them against a real
database as if they were government offices; real desks come from the departments.

    python backend/scripts/gen_demo_district_offices.py
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
districts = yaml.safe_load((ROOT / "specs" / "registry" / "districts.yaml").read_text(encoding="utf-8"))["districts"]
names = [d["name_en"] for d in districts if d["name_en"] != "Bhopal"]
values = ",\n  ".join("('" + n.replace("'", "''") + "')" for n in names)

sql = rf"""-- DEMO ONLY (generated by backend/scripts/gen_demo_district_offices.py): an invented district desk for every department in every district except Bhopal.
-- Needs migration 005. Names copy the Bhopal demo desk of the same department. NOT government data. Undo: DELETE FROM offices WHERE office_name LIKE '%(DEMO)' AND district <> 'Bhopal';

INSERT INTO offices (department, level, code, name, aliases, centroid_lat, centroid_lng, office_name, officer_name, district, active)
SELECT o.department, 'district', o.code || '-' || upper(regexp_replace(d.name, '[^A-Za-z]', '', 'g')), d.name, ARRAY[d.name], NULL, NULL,
       regexp_replace(o.office_name, ' \(DEMO\)$', '') || ', ' || d.name || ' (DEMO)', NULL, d.name, true
FROM offices o
CROSS JOIN (VALUES
  {values}
) AS d(name)
WHERE o.level = 'district' AND o.district = 'Bhopal' AND o.active
ON CONFLICT DO NOTHING;
"""
out = ROOT / "database" / "seed_demo_district_offices.sql"
out.write_text(sql, encoding="utf-8")
print("wrote", out, f"({len(names)} districts)")
