"""Write database/migrations/007_district_desks.sql (and the table in docs/DISTRICT_DESKS.md) from specs/registry/district_desks.yaml.

    python backend/scripts/gen_district_desks.py

For every department with a spec: either one desk in each of the 55 districts (scope: district) or one state desk in the capital (scope: state). Checks first that every
department is covered exactly once, prefixes are unique and the district names match specs/registry/districts.yaml. Safe to re-run: the SQL is idempotent
(ON CONFLICT DO NOTHING) and only ever renames the invented "(DEMO)" desks, never a desk someone has edited.
"""

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SPECS = ROOT / "specs"
DESKS = yaml.safe_load((SPECS / "registry" / "district_desks.yaml").read_text(encoding="utf-8"))
DISTRICTS = yaml.safe_load((SPECS / "registry" / "districts.yaml").read_text(encoding="utf-8"))["districts"]
OUT_SQL = ROOT / "database" / "migrations" / "007_district_desks.sql"
OUT_DOC = ROOT / "docs" / "DISTRICT_DESKS.md"
SKIP = {"human_evaluation"}  # the review queue, not a government department


def q(text: str) -> str:
    return "'" + str(text).replace("'", "''") + "'"


def load_departments() -> dict[str, str]:
    out = {}
    for path in sorted(SPECS.glob("*.yaml")):
        spec = yaml.safe_load(path.read_text(encoding="utf-8"))
        if spec["service"] not in SKIP:
            out[spec["service"]] = spec["department"]
    return out


def validate(departments: dict[str, str]) -> None:
    services = DESKS["services"]
    missing, extra = set(departments) - set(services), set(services) - set(departments)
    if missing or extra:
        sys.exit(f"district_desks.yaml does not match the specs. missing: {sorted(missing)} unknown: {sorted(extra)}")
    prefixes = [v["prefix"] for v in services.values()]
    if len(set(prefixes)) != len(prefixes) or not all(re.fullmatch(r"[A-Z]{2,4}", p) for p in prefixes):
        sys.exit("prefixes must be unique, 2-4 capital letters")
    for name, v in services.items():
        if v["scope"] not in ("district", "state") or not v.get("designation"):
            sys.exit(f"{name}: scope must be district or state and a designation is required")
    codes = [d["code"] for d in DISTRICTS]
    if len(set(codes)) != len(codes) or len(DISTRICTS) != 55:
        sys.exit("districts.yaml must list 55 districts with unique codes")


def build_sql(departments: dict[str, str]) -> str:
    services = DESKS["services"]
    values = ",\n  ".join(f"({d['code']}, {q(d['name_en'])}, {q(d['name_hi'])})" for d in DISTRICTS)
    parts = [
        f"""-- Migration 007: a desk for every department in every district (or one state desk), from specs/registry/district_desks.yaml.
-- GENERATED by backend/scripts/gen_district_desks.py on {DESKS['checked']}: edit the yaml, not this file. Needs migration 005 (offices.district).
-- NOT applied automatically: run once on the Supabase database, after 004 and 005. Safe to re-run (ON CONFLICT DO NOTHING).
--
-- What it does, per department:
--   district scope: one desk "<designation>, <district>" in each of the 55 districts. The invented Bhopal "(DEMO)" desk (migration 004) is renamed to the real designation, so the tickets
--                   already pointing at it keep working. Desks already edited by hand are left alone.
--   state scope:    one state desk (level 'state'); the invented Bhopal "(DEMO)" district desk is switched off (not deleted: tickets may point at it).
-- A desk is a designation, not a person: officer_name stays empty until the department supplies it. Sources and confidence per department: docs/DISTRICT_DESKS.md.
--
-- Not touched: the ward offices (Bhopal demo wards stay as they are; the optional statement at the end switches the invented ones off), block-level offices (not modelled yet).
-- Undo: DELETE FROM offices WHERE level = 'state'; DELETE FROM offices WHERE level = 'district' AND code ~ '-D[0-9]+$';  (renamed Bhopal desks keep their new name)

ALTER TABLE offices DROP CONSTRAINT IF EXISTS offices_level_check;
ALTER TABLE offices ADD CONSTRAINT offices_level_check CHECK (level IN ('ward', 'zone', 'municipal_corp', 'gram_panchayat', 'block', 'district', 'state'));

DROP TABLE IF EXISTS _mp_districts;
CREATE TEMP TABLE _mp_districts (code int, name text, name_hi text);
INSERT INTO _mp_districts (code, name, name_hi) VALUES
  {values};
"""
    ]
    for service, dept in sorted(departments.items(), key=lambda kv: kv[1]):
        v = services[service]
        parts.append(f"\n-- {dept}: {v['designation']} ({v['scope']}, {v['confidence']} confidence)")
        if v["scope"] == "district":
            parts.append(
                f"UPDATE offices SET office_name = {q(v['designation'] + ', Bhopal')}\n"
                f"  WHERE department = {q(dept)} AND level = 'district' AND district = 'Bhopal' AND office_name LIKE '%(DEMO)%';\n"
                f"INSERT INTO offices (department, level, code, name, aliases, office_name, officer_name, district, active)\n"
                f"SELECT {q(dept)}, 'district', {q(v['prefix'] + '-D')} || d.code, d.name, ARRAY[d.name, d.name_hi], {q(v['designation'] + ', ')} || d.name, NULL, d.name, true\n"
                f"FROM _mp_districts d\n"
                f"ON CONFLICT DO NOTHING;"
            )
        else:
            parts.append(
                f"UPDATE offices SET active = false WHERE department = {q(dept)} AND level = 'district' AND office_name LIKE '%(DEMO)%';\n"
                f"INSERT INTO offices (department, level, code, name, aliases, office_name, officer_name, district, active)\n"
                f"VALUES ({q(dept)}, 'state', {q(v['prefix'] + '-STATE')}, 'Madhya Pradesh', ARRAY['Madhya Pradesh', 'Bhopal'], {q(v['designation'])}, NULL, NULL, true)\n"
                f"ON CONFLICT DO NOTHING;"
            )
    parts.append("\nDROP TABLE IF EXISTS _mp_districts;")
    parts.append(
        """
-- Optional, when the real ward / block offices are loaded: switch off the invented Bhopal demo wards of the departments added in migration 004.
-- UPDATE offices SET active = false WHERE level = 'ward' AND office_name LIKE '%(DEMO)%';
"""
    )
    return "\n".join(parts)


def build_table(departments: dict[str, str]) -> str:
    rows = ["| Department | Scope | Desk | Confidence | Seen in detailed / all directories |", "|---|---|---|---|---|"]
    for service, dept in sorted(departments.items(), key=lambda kv: kv[1]):
        v = DESKS["services"][service]
        ev = v["evidence"]
        rows.append(f"| {dept} | {v['scope']} | {v['designation']} | {v['confidence']} | {ev['rich']}/13 · {ev['any']}/45 |")
    return "\n".join(rows)


def main() -> None:
    departments = load_departments()
    validate(departments)
    OUT_SQL.write_text(build_sql(departments), encoding="utf-8")
    n_district = sum(1 for v in DESKS["services"].values() if v["scope"] == "district")
    print(f"wrote {OUT_SQL.name}: {n_district} departments x 55 districts = {n_district * 55} desks, {len(departments) - n_district} state desks")
    if OUT_DOC.exists():
        doc = OUT_DOC.read_text(encoding="utf-8")
        start, end = "<!-- table:start -->", "<!-- table:end -->"
        if start in doc and end in doc:
            head, rest = doc.split(start, 1)
            _, tail = rest.split(end, 1)
            OUT_DOC.write_text(f"{head}{start}\n{build_table(departments)}\n{end}{tail}", encoding="utf-8")
            print("updated the table in", OUT_DOC.name)


if __name__ == "__main__":
    main()
