"""Every department in the routing registry has a spec, an office migration and a four-level route (generated by scripts/gen_department_specs.py)."""

import re
from pathlib import Path

import yaml

from app.intake import load_registry
from app.service_spec import load_specs

ROOT = Path(__file__).resolve().parents[2]
SPECS = load_specs(ROOT / "specs")
REG = load_registry()
ROUTES = yaml.safe_load((ROOT / "specs" / "registry" / "routes.yaml").read_text(encoding="utf-8"))["departments"]
MIGRATION = (ROOT / "database" / "migrations" / "004_all_department_offices.sql").read_text(encoding="utf-8")
LEGACY = {"phe", "energy", "public_works", "urban_development_housing"}  # hand-written specs; offices live in seed.sql / seed_departments.sql


def test_every_registry_department_is_live():
    assert set(REG.live_specs) == set(REG.by_id)
    assert set(REG.live_specs.values()) <= set(SPECS)


def test_every_registry_department_has_a_four_level_route():
    assert set(ROUTES) == set(REG.by_id)
    for dept_id, route in ROUTES.items():
        assert len(route["chain"]) == 4 and all(route["chain"]), dept_id


def test_generated_specs_match_their_routes_and_have_offices():
    for dept_id, spec_id in REG.live_specs.items():
        spec = SPECS[spec_id]
        assert spec.department == ROUTES[dept_id]["department"], dept_id
        if dept_id in LEGACY:
            continue
        assert f"'{spec.department}', 'district'" in MIGRATION, f"{dept_id}: no district office"  # the resolver needs one
        assert MIGRATION.count(f"'{spec.department}', 'ward'") == 5, f"{dept_id}: expected the 5 demo wards"


def test_department_names_are_unique():
    names = [s.department for s in SPECS.values() if s.service != "human_evaluation"]
    assert len(names) == len(set(names))


def test_every_spec_can_be_filled_in():
    for spec in SPECS.values():
        if spec.service == "human_evaluation":
            continue
        issue = spec.field("issue_type") or spec.field("problem")
        assert issue is not None or spec.required_fields(), spec.service
        assert spec.recognise and any(f.type == "location" for f in spec.fields), spec.service


def test_mid_day_meal_routes_to_school_education():
    spec = SPECS[REG.live_specs["school_education"]]
    assert spec.department == "School Education Department"
    values = {v.value for v in spec.field("issue_type").values}
    assert "midday_meal" in values
    assert any("mid day meal" in r.lower() for r in spec.recognise)
    assert re.search(r"Block Education Officer", ROUTES["school_education"]["first_office"])
    assert "Collector" in ROUTES["school_education"]["chain"][3]


# --- the model prompt stays small with dozens of services (Groq answered 413 Payload Too Large with all 50 specs in full) -------------------------------


def test_prompt_is_compact_with_many_services_but_keeps_the_relevant_fields():
    from app import turn_engine as te

    session = te.SessionState(service_id=None, collected_fields={}, awaiting_confirmation=False)
    prompt = te._build_prompt(session, SPECS, "mere gaon ke school me mid day meal nahi mil raha", None, None, [])
    full_all = "\n".join(te._service_block(s) for s in SPECS.values())
    assert len(te._services_text(session, SPECS, "mere gaon ke school me mid day meal nahi mil raha")) < len(full_all) / 3  # was every spec's whole field list
    assert len(prompt) < 16000  # about 5k tokens; with all 50 specs in full Groq answered 413
    assert 'service_id "school_education"' in prompt and "midday_meal" in prompt  # the matching service keeps its allowed values
    assert 'service_id "revenue"' in prompt and "record_error" not in prompt  # an unrelated service is only a one-line entry (its allowed values are not listed)


def test_active_service_always_gets_full_details():
    from app import turn_engine as te

    session = te.SessionState(service_id="labour", collected_fields={}, awaiting_confirmation=False)
    prompt = te._build_prompt(session, SPECS, "haan", None, None, [])
    assert "child_labour" in prompt


def test_few_services_are_listed_in_full_as_before():
    from app import turn_engine as te

    small = {k: SPECS[k] for k in ("water_supply", "electricity", "roads")}
    session = te.SessionState(service_id=None, collected_fields={}, awaiting_confirmation=False)
    prompt = te._build_prompt(session, small, "paani nahi aa raha", None, None, [])
    assert all(te._service_block(s) in prompt for s in small.values())


def test_common_words_do_not_pull_unrelated_services_into_the_prompt():
    import re as _re

    from app import turn_engine as te

    session = te.SessionState(service_id=None, collected_fields={}, awaiting_confirmation=False)
    text = te._services_text(session, SPECS, "हमारे गाँव में मारसाब नहीं आ रहा")
    full = set(_re.findall(r'service_id "(\w+)" \([^)]*\)\. Hints', text))
    assert "water_supply" not in full  # "नहीं आ रहा" is in water's hint but is not a reason to show water in full
    assert "school_education" in full  # the dialect word for teacher is now a hint of its own
