-- Migration 004: DEMO offices for every department that has a generated service spec (scripts/gen_department_specs.py).
-- Same demo wards as seed.sql so a place name routes the same way in every department. DEMO data, NOT from any government list.
-- Safe to run twice (ON CONFLICT DO NOTHING). Undo: DELETE FROM offices WHERE office_name LIKE '%(DEMO)' AND department IN (<these departments>);

INSERT INTO offices (department, level, code, name, aliases, centroid_lat, centroid_lng, office_name, officer_name, active) VALUES
  ('School Education Department', 'district', 'EDU-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Education Officer Office (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'district', 'SCW-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District SC Welfare Officer Office (DEMO)', NULL, true),
  ('Anand Department', 'district', 'ANAND-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Anand Coordinator Office (DEMO)', NULL, true),
  ('AYUSH Department', 'district', 'AYUSH-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District AYUSH Officer Office (DEMO)', NULL, true),
  ('Higher Education Department', 'district', 'HEDU-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Higher Education Officer Office (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'district', 'HORT-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Deputy Director Horticulture Office (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'district', 'IND-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'General Manager District Trade and Industry Centre Office (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'district', 'AGRI-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Deputy Director Agriculture Office (DEMO)', NULL, true),
  ('Mineral Resources Department', 'district', 'MIN-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Mining Officer Office (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'district', 'FCS-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Supply Officer Office (DEMO)', NULL, true),
  ('Home Department (Police)', 'district', 'POL-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Superintendent of Police Office (DEMO)', NULL, true),
  ('Medical Education Department', 'district', 'MEDEDU-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Dean Medical College Office (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'district', 'TRIBAL-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Tribal Welfare Officer Office (DEMO)', NULL, true),
  ('Public Relations Department', 'district', 'PR-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Public Relations Officer Office (DEMO)', NULL, true),
  ('Jail Department', 'district', 'JAIL-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Jail Superintendent Office (district / central jail) (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'district', 'TECH-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Employment Officer Office (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'district', 'NVDA-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Executive Engineer Narmada Valley Office (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'district', 'PRD-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Zila Panchayat CEO Office (DEMO)', NULL, true),
  ('Transport Department', 'district', 'TRN-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Regional Transport Officer Office (DEMO)', NULL, true),
  ('Tourism Department', 'district', 'TOUR-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Tourism Officer Office (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'district', 'AH-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Deputy Director Animal Husbandry Office (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'district', 'OBC-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Backward Classes Welfare Officer Office (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'district', 'ELEC-C-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Election Officer Office (DEMO)', NULL, true),
  ('Public Service Commission', 'district', 'PSC-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'MPPSC Office Indore (DEMO)', NULL, true),
  ('Women and Child Development Department', 'district', 'WCD-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Programme Officer Women and Child Development Office (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'district', 'PES-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Planning Officer Office (DEMO)', NULL, true),
  ('Revenue Department', 'district', 'REV-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Sub-Divisional Magistrate Office (DEMO)', NULL, true),
  ('Public Service Management Department', 'district', 'PSM-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Public Service Management Office (Collectorate) (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'district', 'HLTH-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Chief Medical and Health Officer Office (DEMO)', NULL, true),
  ('Forest Department', 'district', 'FOR-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Divisional Forest Officer Office (DEMO)', NULL, true),
  ('Commercial Tax Department', 'district', 'CTD-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Deputy Commissioner Commercial Tax Office (DEMO)', NULL, true),
  ('Science and Technology Department', 'district', 'DST-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District e-Governance Society Office (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'district', 'FIN-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Treasury Officer Office (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'district', 'LAW-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Legal Services Authority (DEMO)', NULL, true),
  ('Civil Aviation Department', 'district', 'AVI-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Civil Aviation Directorate Office (DEMO)', NULL, true),
  ('Labour Department', 'district', 'LAB-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Assistant Labour Commissioner Office (DEMO)', NULL, true),
  ('Culture Department', 'district', 'CULT-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Culture Officer Office (DEMO)', NULL, true),
  ('Cooperative Department', 'district', 'COOP-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Deputy Registrar Cooperative Societies Office (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'district', 'SJ-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Social Justice Officer Office (DEMO)', NULL, true),
  ('General Administration Department', 'district', 'GAD-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Collectorate (District Magistrate Office) (DEMO)', NULL, true),
  ('MSME Department', 'district', 'MSME-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Trade and Industry Centre (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'district', 'CVI-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Cottage Industries Officer Office (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'district', 'RNW-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'District Renewable Energy Officer Office (DEMO)', NULL, true),
  ('Fisheries Department', 'district', 'FISH-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Assistant Director Fisheries Office (DEMO)', NULL, true),
  ('Food and Drug Administration', 'district', 'FDA-HQ', 'Bhopal', ARRAY['Bhopal'], NULL, NULL, 'Designated Food Safety Officer Office (DEMO)', NULL, true)
ON CONFLICT (department, level, code) DO NOTHING;

INSERT INTO offices (department, level, code, name, aliases, centroid_lat, centroid_lng, office_name, officer_name, active) VALUES
  ('School Education Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Block Education Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('School Education Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Block Education Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('School Education Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Block Education Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('School Education Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Block Education Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('School Education Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Block Education Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Assistant Commissioner Tribal and SC Welfare Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Assistant Commissioner Tribal and SC Welfare Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Assistant Commissioner Tribal and SC Welfare Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Assistant Commissioner Tribal and SC Welfare Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Scheduled Caste Welfare Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Assistant Commissioner Tribal and SC Welfare Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Anand Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Anand Sansthan Block Coordinator - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Anand Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Anand Sansthan Block Coordinator - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Anand Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Anand Sansthan Block Coordinator - Ward मिसरोद (DEMO)', NULL, true),
  ('Anand Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Anand Sansthan Block Coordinator - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Anand Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Anand Sansthan Block Coordinator - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('AYUSH Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'AYUSH Dispensary Medical Officer - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('AYUSH Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'AYUSH Dispensary Medical Officer - Ward रानी कमलापति (DEMO)', NULL, true),
  ('AYUSH Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'AYUSH Dispensary Medical Officer - Ward मिसरोद (DEMO)', NULL, true),
  ('AYUSH Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'AYUSH Dispensary Medical Officer - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('AYUSH Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'AYUSH Dispensary Medical Officer - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Higher Education Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'College Principal Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Higher Education Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'College Principal Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Higher Education Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'College Principal Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Higher Education Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'College Principal Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Higher Education Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'College Principal Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Senior Horticulture Development Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Senior Horticulture Development Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Senior Horticulture Development Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Senior Horticulture Development Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Horticulture and Food Processing Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Senior Horticulture Development Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Trade and Industry Centre - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Trade and Industry Centre - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Trade and Industry Centre - Ward मिसरोद (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Trade and Industry Centre - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Industrial Policy and Investment Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Trade and Industry Centre - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Rural Agriculture Extension Officer / Sub-Divisional Agriculture Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Rural Agriculture Extension Officer / Sub-Divisional Agriculture Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Rural Agriculture Extension Officer / Sub-Divisional Agriculture Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Rural Agriculture Extension Officer / Sub-Divisional Agriculture Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Farmer Welfare and Agriculture Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Rural Agriculture Extension Officer / Sub-Divisional Agriculture Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Mineral Resources Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Mining Inspector Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Mineral Resources Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Mining Inspector Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Mineral Resources Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Mining Inspector Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Mineral Resources Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Mining Inspector Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Mineral Resources Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Mining Inspector Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Supply Inspector / Fair Price Shop Inspector Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Supply Inspector / Fair Price Shop Inspector Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Supply Inspector / Fair Price Shop Inspector Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Supply Inspector / Fair Price Shop Inspector Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Food Civil Supplies Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Supply Inspector / Fair Price Shop Inspector Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Home Department (Police)', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Police Station (Station House Officer) - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Home Department (Police)', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Police Station (Station House Officer) - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Home Department (Police)', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Police Station (Station House Officer) - Ward मिसरोद (DEMO)', NULL, true),
  ('Home Department (Police)', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Police Station (Station House Officer) - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Home Department (Police)', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Police Station (Station House Officer) - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Medical Education Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Medical College Hospital Superintendent Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Medical Education Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Medical College Hospital Superintendent Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Medical Education Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Medical College Hospital Superintendent Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Medical Education Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Medical College Hospital Superintendent Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Medical Education Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Medical College Hospital Superintendent Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Assistant Commissioner Tribal Welfare Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Assistant Commissioner Tribal Welfare Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Assistant Commissioner Tribal Welfare Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Assistant Commissioner Tribal Welfare Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Tribal Affairs Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Assistant Commissioner Tribal Welfare Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Public Relations Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Public Relations Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Public Relations Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Public Relations Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Public Relations Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Public Relations Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Public Relations Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Public Relations Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Public Relations Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Public Relations Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Jail Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Jail Superintendent Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Jail Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Jail Superintendent Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Jail Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Jail Superintendent Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Jail Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Jail Superintendent Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Jail Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Jail Superintendent Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'ITI Principal Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'ITI Principal Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'ITI Principal Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'ITI Principal Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Technical Education Skill and Employment Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'ITI Principal Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Sub-Engineer Narmada Valley Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Sub-Engineer Narmada Valley Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Sub-Engineer Narmada Valley Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Sub-Engineer Narmada Valley Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Narmada Valley Development Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Sub-Engineer Narmada Valley Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Janpad Panchayat CEO Office (block) - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Janpad Panchayat CEO Office (block) - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Janpad Panchayat CEO Office (block) - Ward मिसरोद (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Janpad Panchayat CEO Office (block) - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Panchayat and Rural Development Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Janpad Panchayat CEO Office (block) - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Transport Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'RTO Inspector Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Transport Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'RTO Inspector Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Transport Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'RTO Inspector Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Transport Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'RTO Inspector Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Transport Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'RTO Inspector Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Tourism Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Tourism Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Tourism Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Tourism Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Tourism Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Tourism Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Tourism Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Tourism Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Tourism Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Tourism Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Veterinary Hospital / Veterinary Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Veterinary Hospital / Veterinary Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Veterinary Hospital / Veterinary Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Veterinary Hospital / Veterinary Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Animal Husbandry Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Veterinary Hospital / Veterinary Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Assistant Commissioner Backward Classes Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Assistant Commissioner Backward Classes Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Assistant Commissioner Backward Classes Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Assistant Commissioner Backward Classes Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Backward Classes and Minority Welfare Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Assistant Commissioner Backward Classes Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Booth Level Officer / Electoral Registration Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Booth Level Officer / Electoral Registration Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Booth Level Officer / Electoral Registration Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Booth Level Officer / Electoral Registration Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('State Election Commission and Electoral Roll', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Booth Level Officer / Electoral Registration Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Public Service Commission', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'MPPSC Office Indore - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Public Service Commission', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'MPPSC Office Indore - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Public Service Commission', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'MPPSC Office Indore - Ward मिसरोद (DEMO)', NULL, true),
  ('Public Service Commission', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'MPPSC Office Indore - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Public Service Commission', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'MPPSC Office Indore - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Women and Child Development Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'CDPO Office (Child Development Project Officer) - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Women and Child Development Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'CDPO Office (Child Development Project Officer) - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Women and Child Development Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'CDPO Office (Child Development Project Officer) - Ward मिसरोद (DEMO)', NULL, true),
  ('Women and Child Development Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'CDPO Office (Child Development Project Officer) - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Women and Child Development Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'CDPO Office (Child Development Project Officer) - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Statistics Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Statistics Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Statistics Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Statistics Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Planning Economics and Statistics Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Statistics Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Revenue Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Tehsil Office (Tehsildar) - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Revenue Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Tehsil Office (Tehsildar) - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Revenue Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Tehsil Office (Tehsildar) - Ward मिसरोद (DEMO)', NULL, true),
  ('Revenue Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Tehsil Office (Tehsildar) - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Revenue Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Tehsil Office (Tehsildar) - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Public Service Management Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Designated Officer of the concerned service - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Public Service Management Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Designated Officer of the concerned service - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Public Service Management Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Designated Officer of the concerned service - Ward मिसरोद (DEMO)', NULL, true),
  ('Public Service Management Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Designated Officer of the concerned service - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Public Service Management Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Designated Officer of the concerned service - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Block Medical Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Block Medical Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Block Medical Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Block Medical Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Public Health and Family Welfare Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Block Medical Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Forest Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Forest Ranger Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Forest Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Forest Ranger Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Forest Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Forest Ranger Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Forest Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Forest Ranger Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Forest Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Forest Ranger Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Commercial Tax Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Commercial Tax Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Commercial Tax Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Commercial Tax Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Commercial Tax Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Commercial Tax Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Commercial Tax Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Commercial Tax Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Commercial Tax Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Commercial Tax Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Science and Technology Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District e-Governance Society Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Science and Technology Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District e-Governance Society Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Science and Technology Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District e-Governance Society Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Science and Technology Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District e-Governance Society Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Science and Technology Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District e-Governance Society Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Treasury Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Treasury Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Treasury Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Treasury Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Finance Department and Treasury', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Treasury Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Legal Services Authority - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Legal Services Authority - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Legal Services Authority - Ward मिसरोद (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Legal Services Authority - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Law and Legislative Affairs Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Legal Services Authority - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Civil Aviation Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Civil Aviation Directorate Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Civil Aviation Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Civil Aviation Directorate Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Civil Aviation Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Civil Aviation Directorate Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Civil Aviation Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Civil Aviation Directorate Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Civil Aviation Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Civil Aviation Directorate Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Labour Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Labour Inspector Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Labour Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Labour Inspector Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Labour Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Labour Inspector Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Labour Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Labour Inspector Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Labour Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Labour Inspector Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Culture Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Culture Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Culture Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Culture Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Culture Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Culture Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Culture Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Culture Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Culture Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Culture Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Cooperative Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Cooperative Inspector Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Cooperative Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Cooperative Inspector Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Cooperative Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Cooperative Inspector Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Cooperative Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Cooperative Inspector Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Cooperative Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Cooperative Inspector Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Block Social Security Officer / Gram Panchayat Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Block Social Security Officer / Gram Panchayat Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Block Social Security Officer / Gram Panchayat Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Block Social Security Officer / Gram Panchayat Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Social Justice and Disability Welfare Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Block Social Security Officer / Gram Panchayat Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('General Administration Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Tehsil / SDM Office (Designated Officer) - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('General Administration Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Tehsil / SDM Office (Designated Officer) - Ward रानी कमलापति (DEMO)', NULL, true),
  ('General Administration Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Tehsil / SDM Office (Designated Officer) - Ward मिसरोद (DEMO)', NULL, true),
  ('General Administration Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Tehsil / SDM Office (Designated Officer) - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('General Administration Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Tehsil / SDM Office (Designated Officer) - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('MSME Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Trade and Industry Centre - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('MSME Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Trade and Industry Centre - Ward रानी कमलापति (DEMO)', NULL, true),
  ('MSME Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Trade and Industry Centre - Ward मिसरोद (DEMO)', NULL, true),
  ('MSME Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Trade and Industry Centre - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('MSME Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Trade and Industry Centre - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Cottage Industries Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Cottage Industries Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Cottage Industries Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Cottage Industries Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Cottage and Village Industries Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Cottage Industries Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'District Renewable Energy Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'District Renewable Energy Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'District Renewable Energy Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'District Renewable Energy Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('New and Renewable Energy Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'District Renewable Energy Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Fisheries Department', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Assistant Director Fisheries Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Fisheries Department', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Assistant Director Fisheries Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Fisheries Department', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Assistant Director Fisheries Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Fisheries Department', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Assistant Director Fisheries Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Fisheries Department', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Assistant Director Fisheries Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true),
  ('Food and Drug Administration', 'ward', '1', 'महात्मा गांधी', ARRAY['Mahatma Gandhi'], NULL, NULL, 'Food Safety Officer Office - Ward महात्मा गांधी (DEMO)', NULL, true),
  ('Food and Drug Administration', 'ward', '24', 'रानी कमलापति', ARRAY['Rani Kamlapati', 'Habibganj'], NULL, NULL, 'Food Safety Officer Office - Ward रानी कमलापति (DEMO)', NULL, true),
  ('Food and Drug Administration', 'ward', '52', 'मिसरोद', ARRAY['Misrod'], NULL, NULL, 'Food Safety Officer Office - Ward मिसरोद (DEMO)', NULL, true),
  ('Food and Drug Administration', 'ward', '60', 'गोविंदपुरा', ARRAY['Govindpura'], NULL, NULL, 'Food Safety Officer Office - Ward गोविंदपुरा (DEMO)', NULL, true),
  ('Food and Drug Administration', 'ward', '80', 'सर्वधर्म कोलार', ARRAY['Sarvadharm Kolar', 'Kolar Road'], NULL, NULL, 'Food Safety Officer Office - Ward सर्वधर्म कोलार (DEMO)', NULL, true)
ON CONFLICT (department, level, code) DO NOTHING;